### PR TITLE
Add Omeka 4 to contraints

### PR DESCRIPTION
**Pull request by waynegraham**
Adds Omeka 4.0.0 to the list of Omeka versions (`omeka_version_constraint`).

### CODE REVIEW

**Comment by waynegraham** [comment]
I didn't bump the version with this, but it should probably be at least at the patch level.

**Comment by jakeparis** [comment]
I tried applying this PR manually to a freshly downloaded version of this module in an Omeka 4 instance. I got the following error, which I _assume_ means that this module is not compatible with Omeka 4? 

```
Error: Class "FieldAsTags\Module" not found in /the/path/to/my/photos/application/src/Module/Manager.php:354
Stack trace:
#0 /the/path/to/my/photos/application/src/Module/Manager.php(225): Omeka\Module\Manager->getModuleObject(Object(Omeka\Module\Module))
#1 /the/path/to/my/photos/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#2 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->installAction()
#3 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#4 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#5 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#6 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#7 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /the/path/to/my/photos/index.php(21): Laminas\Mvc\Application->run()
#11 {main}
```

**Comment by Boca13** [comment]
Hello,

Thank you both for your input and sorry for the delay. We needed to update the item browse view to make it compatible with Omeka S 4, so it needed a bit more than the version constraint changed.

The new version has already been released. Let me know if it works for you!
https://github.com/Libnamic/Omeka-S-FieldAsTags/releases/tag/1.1.0

**Comment by jakeparis** [comment]
Hi @Boca13 , I've updated to version 1.1.0 (and upgraded Omeka to 4.0.4). When I hit the install button in the Omeka admin UI, I get the same message as before: 
```
 Error
Class "FieldAsTags\Module" not found

Details:

Error: Class "FieldAsTags\Module" not found in /the/path/to/my/photos/application/src/Module/Manager.php:354
Stack trace:
#0 /the/path/to/my/photos/application/src/Module/Manager.php(225): Omeka\Module\Manager->getModuleObject(Object(Omeka\Module\Module))
#1 /the/path/to/my/photos/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#2 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->installAction()
#3 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#4 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#5 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#6 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#7 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /the/path/to/my/photos/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /the/path/to/my/photos/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /the/path/to/my/photos/index.php(21): Laminas\Mvc\Application->run()
#11 {main}
```

I installed a fresh copy of FieldAsTags, but that didn't help. Do you have any ideas on what is needed here?

**Comment by Boca13** [comment]
I think it's a problem with the folder name. Can you check that the module folder is exactly "FieldsAsTags"? Field**s**, in plural. The folder should have the same name as the module, which is like that. I am aware that the repository name is **Field**AsTags and considered renaming it, but that operation might cause many problems.

**Comment by jakeparis** [comment]
Yes, that was exactly it. When I cloned it, I removed the `Omeka-S` prefix, but didn't notice that `Field` wasn't plural. Thank you!

Perhaps that little step should be noted in the README on installing from git.

`git clone https://github.com/Libnamic/Omeka-S-FieldAsTags.git FieldsAsTags`

**Comment by jakeparis** [comment]
Added https://github.com/Libnamic/Omeka-S-FieldAsTags/pull/3 to make this a little clearer.

**Pull request closed without merging**
